module.exports = {
    NEW_MESSAGE: 'NEW_MESSAGE',
    CHECK_NEW_FILES: 'CHECK_NEW_FILES',
    AUDIO_FILES: 'AUDIO_FILES',
    LABELS_TO_PLAY: 'LABELS_TO_PLAY',
    CHECK_NEW_ORDERS: 'CHECK_NEW_ORDERS',
};