module.exports = {
    EYES_ON: 'EYES_ON',
    MOUTH_ON: 'MOUTH_ON',
    EYES_OFF: 'EYES_OFF',
    MOUTH_OFF: 'MOUTH_OFF',
    SERVO_L_READY: 'SERVO_L_READY',
    SERVO_R_READY: 'SERVO_R_READY',
    SONIC_CROSSED: 'SONIC_CROSSED',
    FINISH_PATROL: 'FINISH_PATROL',
    TOTAL_END_AUDIO: 'TOTAL_END_AUDIO',
    USER_COMMAND: 'USER_COMMAND',
};